# Generated by Django 4.2.16 on 2026-10-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0006_alter_dailyentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='receipt_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
